---
title: "GPA Projection"
---

```{r setStudent, include=FALSE}
## ENTER file name, student's name, and last term of observed
##   grades (NULL if no projections) here
fn <- "Student1Grades.xlsx"
sn <- "Student One"
lastterm <- NULL
```
```{r echo=FALSE, eval=FALSE}
## Save file and run (CTRL-ALT-C) previous and this to create doc
rmarkdown::render("NC_GPA_Calculator.Rmd","pdf_document",
                  paste0(sn,"_",format(Sys.time(),'%d_%b_%y'),".pdf")) 
```




```{r setup, include=FALSE}
## Set knitr and R options
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,comment="",
                      fig.width=4.25,fig.height=2.75)
options(width=120)

## Load packages
library(readxl)
library(FSA)
library(dplyr)
library(magrittr)
library(ggplot2)

## Setup Grade Points
grdltrs <- c("A","A-","B+","B","B-","C+","C","C-","D+","D",
             "F","I","AU","W","S","U")
grdpts <- c(4,3.7,3.3,3,2.7,2.3,2,1.7,1.3,1,
            0,0,0,0,0,0)
sems <- c("TR","SU","F","W","S")
yrs <- 10:25
trmord <- paste0(rep(sems,length(yrs)),rep(yrs,each=length(sems)))

## Plotting options
clrs <- c("black","steelblue3")
theme_set(theme_bw())
```
```{r prepData, include=FALSE}
## Credits = "term attempted credits" ... credits for classes enrolled in
## EarnCr = "term earned credits" ... Credits w/0 W, I, AU, F
## GPACr = "term gpa credits" ... for computing GPA (excluded W, I, AU, S, U)
## QPts = "term quality points" ... grade * credits
##
## AttCr2 = "career attempted credits" ... Credits adusted for repeated courses
## EarnCr2 = "career earned credits" ... EarnedCr adjusted for repeated courses
## GPACr2 = "career gpa credits" ... GPACr adjusted for repeated courses
## QPts2 = "career quality points" ... QPts adjusted for repeated courses
##
d <- read_excel(fn,col_types=c("numeric","text","text","numeric","text",
                               "text","text","text","text")) %>%
  rename(Maj1=Major1,Maj2=Major2,Reptd=Repeated) %>%
  mutate(AY=AY-2000,
         Sem=ifelse(capFirst(Sem)=="Transfer","TR",Sem),
         Term=droplevels(ordered(paste0(Sem,AY),levels=trmord)),
         EarnCr=ifelse(Grade %in% c("F","I","AU","W"),0,Credits),
         GPACr=ifelse(Grade %in% c("I","AU","W","S","U"),0,Credits),
         QPts=mapvalues(Grade,from=grdltrs,grdpts,warn_missing=FALSE),
         QPts=as.numeric(QPts)*Credits,
         AttCr2=ifelse(is.na(Reptd) | Grade %in% c("W","I"),Credits,0),
         EarnCr2=ifelse(is.na(Reptd),EarnCr,0),
         GPACr2=ifelse(is.na(Reptd),GPACr,0),
         QPts2=ifelse(is.na(Reptd),QPts,0)) %>%
  select(-AY,-Sem) %>%
  arrange(Term,Course)

## Find lastterm if is.null(lastterm)
if (is.null(lastterm)) lastterm <- levels(d$Term)[length(levels(d$Term))]

## Determine if major information is provided
doMaj1 <- any(!is.na(d$Maj1))
doMaj2 <- any(!is.na(d$Maj2))
```


## Notes

* **Student**: `r sn`.
* **Date**: `r format(Sys.time(), '%A %B %d %Y, %X')`.
* **Last Term of Observed Grades**: `r lastterm`.
* **File**: `r basename(fn)`.
* GPA and earned credit projections assume the following:

```{r}
tmp <- d %>%
  filterD(Term>ordered(lastterm,levels(Term))) %>%
  select(Term,Course,AttCr2,EarnCr2,GPACr2,Grade,QPts2,Reptd,Maj1,Maj2,Notes) %>%
  rename(Att_Cr=AttCr2,Earn_Cr=EarnCr2,GPA_Cr=GPACr2,Q_Pts=QPts2) %>%
  arrange(Term,Maj1,Maj2,Course) %>%
  as.data.frame()
for (i in levels(tmp$Term)) {
  print(filterD(tmp,Term==i),row.names=FALSE,na.print="")
  cat("\n")
}
```

\newpage

## Projections

```{r TotalSum, include=FALSE}
## Overall (all courses) summary
dsum1 <- d %>%
  group_by(Term) %>%
  summarize(tAttCr=sum(Credits,na.rm=TRUE),
            tEarnCr=sum(EarnCr,na.rm=TRUE),
            tGPACr=sum(GPACr,na.rm=TRUE),
            tQPts=sum(QPts,na.rm=TRUE),
            tAttCr2=sum(AttCr2,na.rm=TRUE),
            tEarnCr2=sum(EarnCr2,na.rm=TRUE),
            tGPACr2=sum(GPACr2,na.rm=TRUE),
            tQPts2=sum(QPts2,na.rm=TRUE)) %>%
  mutate(tGPA=ifelse(tGPACr==0,0,tQPts/tGPACr),
         cAttCr=cumsum(tAttCr2),
         cEarnCr=cumsum(tEarnCr2),
         cGPACr=cumsum(tGPACr2),
         cQPts=cumsum(tQPts2),
         cGPA=ifelse(cGPACr==0,0,cQPts/cGPACr),
         Projected=Term>ordered(lastterm,levels(Term))) %>%
  select(Term,Projected,tAttCr,tEarnCr,tGPACr,tQPts,tGPA,
         cAttCr,cEarnCr,cGPACr,cQPts,cGPA)
```

```{r CareerGPAPlot}
tmp <- filter(dsum1,!grepl("TR",Term))
pCGPA <- tmp %>%
  ggplot(aes(x=Term,y=cGPA,group=1,color=Projected)) +
  geom_hline(yintercept=2.0,color="red",linetype="dashed") +
  geom_line(size=0.8) +
  geom_point(size=1.5,fill="white",pch=21) +
  scale_color_manual(values=clrs) +
  scale_x_discrete("Term") +
  scale_y_continuous("Career Overall GPA",expand=c(0,0.5)) +
  guides(color=FALSE)
pCGPA + 
  geom_text(data=top_n(tmp,1,wt=Term),
            aes(x=Term,label=formatC(cGPA,format="f",digits=4)),
            size=3,nudge_y=0.1)
```

```{r CreditsPlot}
dsum1 %>%
  top_n(8,wt=Term) %>%
  ggplot(aes(x=Term,y=cEarnCr,fill=Projected)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values=clrs) +
  scale_y_continuous("Career Earned Credits",limits=c(0,150),
                     expand=c(0,0)) +
  geom_hline(yintercept=124,color="red",linetype="dashed") +
  guides(fill=FALSE) +
  geom_text(data=top_n(dsum1,1,wt=Term),aes(x=Term,label=cEarnCr),
            size=3,nudge_y=5)
```

```{r Maj1Sum, eval=doMaj1}
## Major courses summary
dsumMjr1 <- d %>%
  filter(Maj1 %in% c("YES","Yes","yes")) %>%
  group_by(Term) %>%
  summarize(tAttCr=sum(Credits,na.rm=TRUE),
            tEarnCr=sum(EarnCr,na.rm=TRUE),
            tEarnCr2=sum(EarnCr2,na.rm=TRUE),
            tGPACr=sum(GPACr,na.rm=TRUE),
            tGPACr2=sum(GPACr2,na.rm=TRUE),
            tQPts=sum(QPts,na.rm=TRUE),
            tQPts2=sum(QPts2,na.rm=TRUE)) %>%
  mutate(tGPA=ifelse(tGPACr==0,0,tQPts/tGPACr),
         cAttCr=cumsum(tAttCr),
         cEarnCr=cumsum(tEarnCr2),
         cGPACr=cumsum(tGPACr2),
         cQPts=cumsum(tQPts2),
         cGPA=ifelse(cGPACr==0,0,cQPts/cGPACr),
         Projected=Term>ordered(lastterm,levels(Term))) %>%
  select(Term,Projected,tAttCr,tEarnCr,tGPACr,tQPts,tGPA,
         cAttCr,cEarnCr,cGPACr,cQPts,cGPA)
```

```{r Maj1GPAPlot, eval=doMaj1}
tmp <- filterD(dsumMjr1,!grepl("TR",Term))
pCGPA %+% 
  tmp +
  geom_text(data=top_n(tmp,1,wt=Term),
            aes(x=Term,group=1,label=formatC(cGPA,format="f",digits=4)),
            size=3,nudge_y=0.1)
```

\newpage

## Major GPA Details

```{r MajorTranscript, eval=doMaj1}
## Print course-level summaries for courses in major
d %>%
  filterD(capFirst(Maj1)=="Yes") %>%
  select(Term,Course,AttCr2,EarnCr2,GPACr2,Grade,QPts2,Reptd,Maj1,Maj2,Notes) %>%
  rename(Att_Cr=AttCr2,Earn_Cr=EarnCr2,GPA_Cr=GPACr2,Q_Pts=QPts2) %>%
  as.data.frame() %>%
  print(row.names=FALSE,na.print="")

# Find and print career summaries at end of each term for major courses
csumMjr1 <- dsumMjr1 %>%
  mutate(Type="Maj1") %>% 
  select(Term,Type,cAttCr,cEarnCr,cGPACr,cQPts,cGPA,Projected) %>%
  as.data.frame()
names(csumMjr1) <- c("Term","Type","Att Cr","Earn Cr",
                    "GPA Cr","Qaul Pts","GPA","Projected")
print(csumMjr1,row.names=FALSE,na.print="")
```

\newpage

# Transcript Details

```{r Transcript}
## All of this is for interleaving term, major, and career info
dterm <- dsum1 %>%
  mutate(Type="Term") %>% 
  select(Term,Type,tAttCr,tEarnCr,tGPACr,tQPts,tGPA,Projected)
dcareer <- dsum1 %>%
  mutate(Type="Career") %>% 
  select(Term,Type,cAttCr,cEarnCr,cGPACr,cQPts,cGPA,Projected)
names(dterm) <- names(dcareer) <- c("Term","Type","Att Cr","Earn Cr",
                                    "GPA Cr","Qaul Pts","GPA","Projected")
dsum3 <- rbind(dterm,dcareer)

if (doMaj1) dsum3 <- rbind(dsum3,csumMjr1)

if (doMaj2) {
  csumMjr2 <- dsumMjr2 %>%
    mutate(Type="Maj2") %>% 
    select(Term,Type,cAttCr,cEarnCr,cGPACr,cQPts,cGPA,Projected)
    names(csumMjr2) <- names(dsum3)
    dsum3 <- rbind(dsum3,csumMjr2)
}

dsum3 %<>%
  mutate(Term=droplevels(ordered(Term,levels=trmord))) %>%
  arrange(Term,desc(Type)) %>%
  filter(!(grepl("TR",Term) & Type=="Term")) %>%
  select(-Projected) %>%
  as.data.frame()

d2 <- d %>%
  select(Term,Course,AttCr2,EarnCr2,GPACr2,Grade,QPts2,Reptd,Maj1,Maj2,Notes) %>%
  rename(Att_Cr=AttCr2,Earn_Cr=EarnCr2,GPA_Cr=GPACr2,Q_Pts=QPts2) %>%
  arrange(Term,Maj1,Maj2) %>%
  as.data.frame()

for (i in levels(d2$Term)) {
  cat("====== Term:",ifelse(i>ordered(lastterm,levels(d2$Term)),
                        paste(i,"***PROJECTED*** "),
                        paste(i,"")),rep("=",50),"\n",sep="")
  print(filterD(d2,Term==i)[,-1],row.names=FALSE,na.print="",digits=4)
  cat("----\n")
  print(filterD(dsum3,Term==i)[,-1],row.names=FALSE,na.print="",digits=4)
  cat("\n\n")
}
```
